In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pytz
%matplotlib inline
import json
from datetime import datetime, timedelta
import pickle

In [21]:
#Se lee el dataset de portflap, primero se lo convirtio de csv a xlsx para corregir un problema relaciona a date_modified
df_3 = pd.read_excel('portflap_dataset31.xls')

In [22]:
#Se cambian los NAN por 0
df_3 = df_3.fillna(0)

In [23]:
df_3.describe()

,as_number,fib.checksum_error_packets,fib.df_unreachable_packets,fib.discard_packets,fib.encapsulation_failure_packets,fib.fragmenation_consumed_packets,fib.gre_error_drop,fib.gre_lookup_failed_drop,fib.incomplete_adjacency_packets,fib.lisp_decap_error_drops,...,fib.unsupported_feature_packets,rib.active_routes_count,rib.backup_routes_count,rib.deleted_routes_count,rib.paths_count,rib.protocol_route_memory,rib.routes_counts,router_id,total_paths,total_prefixes
count,802.0,802.0,802.0,802.0,802.0,802.0,802.0,802.0,802.0,802.0,...,802.0,802.000000,802.000000,802.000000,802.000000,802.000000,802.000000,802.000000,802.000000,802.000000
mean,65000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.900249,0.402743,0.067332,10.302993,1654.403990,10.370324,1112.498753,37.271820,28.498753
std,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.769276,0.740242,0.400318,1.013869,166.807031,1.098753,1.118731,4.347965,1.660475
min,65000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.000000,0.000000,0.000000,9.000000,1440.000000,9.000000,1111.000000,28.000000,26.000000
25%,65000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.000000,0.000000,0.000000,10.000000,1600.000000,10.000000,1111.250000,34.000000,26.500000
50%,65000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,10.000000,0.000000,0.000000,10.000000,1600.000000,10.000000,1112.500000,36.000000,29.000000
75%,65000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,10.750000,1.000000,0.000000,10.750000,1720.000000,10.750000,1113.000000,42.000000,30.000000
max,65000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,11.000000,3.000000,3.000000,14.000000,2240.000000,14.000000,1114.000000,42.000000,30.000000

In [24]:
df_null_values = [
    'fib.checksum_error_packets',
    'fib.df_unreachable_packets',
    'fib.discard_packets',
    'fib.encapsulation_failure_packets',
    'fib.fragmenation_consumed_packets',
    'fib.gre_error_drop',
    'fib.gre_lookup_failed_drop',
    'fib.incomplete_adjacency_packets',
    'fib.lisp_decap_error_drops',
    'fib.lisp_encap_error_drops',
    'fib.lisp_punt_drops',
    'fib.mpls_disabled_interface',
    'fib.multi_label_drops',
    'fib.no_route_packets',
    'fib.null_packets',
    'fib.punt_unreachable_packets',
    'fib.rp_destination_drop_packets',
    'fib.rpf_check_failure_packets',
    'fib.total_number_of_drop_packets',
    'fib.unresolved_prefix_packets',
    'fib.unsupported_feature_packets',
    'as_number',
    'interfaces',
    'fib.node_name',
    'rib.af_name',
    'rib.as_number',
    'rib.route_table_name',
    'timestamp',
    ]
for key in df_null_values:
    if key in df_3.columns:
        
        del df_3[key]
df_3.describe()

,rib.active_routes_count,rib.backup_routes_count,rib.deleted_routes_count,rib.paths_count,rib.protocol_route_memory,rib.routes_counts,router_id,total_paths,total_prefixes
count,802.000000,802.000000,802.000000,802.000000,802.000000,802.000000,802.000000,802.000000,802.000000
mean,9.900249,0.402743,0.067332,10.302993,1654.403990,10.370324,1112.498753,37.271820,28.498753
std,0.769276,0.740242,0.400318,1.013869,166.807031,1.098753,1.118731,4.347965,1.660475
min,9.000000,0.000000,0.000000,9.000000,1440.000000,9.000000,1111.000000,28.000000,26.000000
25%,9.000000,0.000000,0.000000,10.000000,1600.000000,10.000000,1111.250000,34.000000,26.500000
50%,10.000000,0.000000,0.000000,10.000000,1600.000000,10.000000,1112.500000,36.000000,29.000000
75%,10.750000,1.000000,0.000000,10.750000,1720.000000,10.750000,1113.000000,42.000000,30.000000
max,11.000000,3.000000,3.000000,14.000000,2240.000000,14.000000,1114.000000,42.000000,30.000000

In [25]:
#Se visualizan las columnas en jupyter no es necesario
#df_3.columns

In [26]:
#Se visualiza parcialmete en jupyter no es necesario
#df_3

In [27]:
#Se modifica el tipo de dato de la columna date_modified para que sea tratada como fecha
df_3["date_modified"] = pd.to_datetime(df_3["date_modified"], format="%Y-%m-%dT%H:%M:%S")
df_3['date_modified'] = pd.to_datetime(df_3['date_modified'].astype('int64'), unit='ns')
#print(df_3['date_modified'].head(5))

In [28]:
#se carga el archivo con las marcas de los eventos anomalos 
#Importante deberan tener una cabecera de event y tiempo si se seguira con los siguiente
dg3=pd.read_excel('portflap_events32.xls').dropna(axis=1, how='all')

In [29]:
#Se visualiza que marcas existe es opcional
#dg3

In [30]:
#Se modifica el tipo de dato de la columna tiempo para que sea tratada como fecha
dg3["tiempo"] = pd.to_datetime(dg3["tiempo"], format="%Y-%m-%dT%H:%M:%S")
dg3['tiempo'] = pd.to_datetime(dg3['tiempo'].astype('int64'), unit='ns')

In [31]:
#Se itera en el rango del dataset de portflap y tambien por el de eventos con el fin de si una marca de tiempo del dataset de 
#port flap corresponda a una de las marcas se la catalogue como anomalia al colocar un numero 1 
#Se realizo de esta manera debido a como estaba estructurado el documento que recopilaba las marcas de tiempo de eventos anomalos
d_df3=df_3
d_df_gt3=dg3

for i in range(len(d_df3)):
    d_df3.loc[i,"Anomaly"] = "0";
#sera 1
for i in range(len(d_df3)):
    for j in range(0,len(d_df_gt3),2):
        if((d_df3.loc[i,"date_modified"]>d_df_gt3.loc[j,"tiempo"]) & (d_df3.loc[i,"date_modified"]<d_df_gt3.loc[j+1,"tiempo"])):
            d_df3.loc[i,"Anomaly"] = "1";

In [32]:
#Para visualizar que se hizo correctamente se imprimen el numero de anomalias en le dataset, opcional este paso
d_df3

,date_modified,rib.active_routes_count,rib.backup_routes_count,rib.deleted_routes_count,rib.paths_count,rib.protocol_route_memory,rib.routes_counts,router_id,total_paths,total_prefixes,Anomaly
0,2022-08-28 21:43:30.000,10,0,0,10,1600,10,1111,34,26,0
1,2022-08-28 21:43:31.867,11,0,0,11,1760,11,1113,42,30,0
2,2022-08-28 21:43:43.607,9,1,0,10,1600,10,1112,42,30,0
3,2022-08-28 21:43:57.058,10,0,0,10,1600,10,1111,34,26,0
4,2022-08-28 21:43:58.636,11,0,0,11,1760,11,1113,42,30,0
...,...,...,...,...,...,...,...,...,...,...,...
797,2022-08-28 23:06:11.574,10,0,0,10,1600,10,1114,36,28,0
798,2022-08-28 23:06:20.184,9,1,0,10,1600,10,1112,42,30,0
799,2022-08-28 23:06:34.642,10,0,0,10,1600,10,1111,34,26,0
800,2022-08-28 23:06:36.287,11,0,0,11,1760,11,1113,42,30,0
801,2022-08-28 23:06:37.811,10,0,0,10,1600,10,1114,36,28,0

In [33]:
d_df3.columns

Index(['date_modified', 'rib.active_routes_count', 'rib.backup_routes_count',
       'rib.deleted_routes_count', 'rib.paths_count',
       'rib.protocol_route_memory', 'rib.routes_counts', 'router_id',
       'total_paths', 'total_prefixes', 'Anomaly'],
      dtype='object')

In [34]:
# no se crea un nuevo dataset vacio porque en el anterior estaban agrupadas las interfaces
df2 = pd.DataFrame(columns=['date_modified', 'rib.active_routes_count', 'rib.backup_routes_count',
                            'rib.deleted_routes_count', 'rib.paths_count',
                            'rib.protocol_route_memory', 'rib.routes_counts', 'router_id',
                            'total_paths', 'total_prefixes', 'Anomaly'])
df2

Empty DataFrame
Columns: [date_modified, rib.active_routes_count, rib.backup_routes_count, rib.deleted_routes_count, rib.paths_count, rib.protocol_route_memory, rib.routes_counts, router_id, total_paths, total_prefixes, Anomaly]
Index: []

In [35]:
#variable de la columnas a usar
cols = ['date_modified', 'rib.active_routes_count', 'rib.backup_routes_count',
        'rib.deleted_routes_count', 'rib.paths_count',
        'rib.protocol_route_memory', 'rib.routes_counts', 'router_id',
        'total_paths', 'total_prefixes', 'Anomaly']

In [36]:
# se itera en el anterior dataset con la finalidad de que por cada router se agreguen sus filas para lasinterfaces
# , si las interfaces vinieron como 0 por el dropna se coloca sus datos con 0
# filter_df = d_df3['router_id'] == 1112
# d_df3 = d_df3[filter_df]
# a = d_df3['date_modified'] 
# b = df_3['date_modified']
# df3 = df_3.replace(b,a)
filter_df = df_3['router_id'] == 1113
df_3 = df_3[filter_df]
for i in df_3.index:

    new_row = [df_3[col][i] for col in cols]
        
    new_df = pd.DataFrame([new_row], columns=cols)

    df2 = pd.concat([df2, new_df], ignore_index = True)


# for index, row in df_3.iterrows():
#     if df_3["router_id"][index] is not None:
#         new_row = row
#         print(row, type(row))
#         new_df = pd.DataFrame([new_row], columns=cols)
#         if df_3["router_id"][index] == '1111':
#             df2 = pd.concat([df2, new_df], ignore_index = True)
#             df2 = pd.concat([df2, new_df], ignore_index = True)
#         elif df_3["router_id"][index] == '1112':
#             df2 = pd.concat([df2, new_df], ignore_index = True)
#             df2 = pd.concat([df2, new_df], ignore_index = True)
#             df2 = pd.concat([df2, new_df], ignore_index = True)
#             df2 = pd.concat([df2, new_df], ignore_index = True)
#         elif df_3["router_id"][index] == '1113':
#             df2 = pd.concat([df2, new_df], ignore_index = True)
#             df2 = pd.concat([df2, new_df], ignore_index = True)
#             df2 = pd.concat([df2, new_df], ignore_index = True)
#         elif df_3["router_id"][index] == '1114':
#             df2 = pd.concat([df2, new_df], ignore_index = True)
#             df2 = pd.concat([df2, new_df], ignore_index = True)

In [37]:
#se visuaiiza que ahora el numero de elementos aumento al separar los la interface, es opcional este paso
df_3

,date_modified,rib.active_routes_count,rib.backup_routes_count,rib.deleted_routes_count,rib.paths_count,rib.protocol_route_memory,rib.routes_counts,router_id,total_paths,total_prefixes,Anomaly
1,2022-08-28 21:43:31.867,11,0,0,11,1760,11,1113,42,30,0
4,2022-08-28 21:43:58.636,11,0,0,11,1760,11,1113,42,30,0
9,2022-08-28 21:44:24.649,11,0,0,11,1760,11,1113,42,30,0
12,2022-08-28 21:44:44.813,11,0,0,11,1760,11,1113,42,30,0
16,2022-08-28 21:45:11.627,11,0,0,11,1760,11,1113,42,30,0
...,...,...,...,...,...,...,...,...,...,...,...
784,2022-08-28 23:04:56.832,11,0,0,11,1760,11,1113,42,30,0
788,2022-08-28 23:05:22.985,11,0,0,11,1760,11,1113,42,30,0
793,2022-08-28 23:05:50.053,11,0,0,11,1760,11,1113,42,30,0
796,2022-08-28 23:06:10.064,11,0,0,11,1760,11,1113,42,30,0
800,2022-08-28 23:06:36.287,11,0,0,11,1760,11,1113,42,30,0

In [38]:
#se guarda el dataframe creado de la anomalia, si se quiere aÃ±adir otra, se debera realizar los pasos anteriores y 
#luego concatenar los dataframe antes de guardar 
pickle.dump(df_3, open( "preprocessedlfinalr10.pkl", "wb"), protocol=-1)